node_number : 3
node_port : 8083
owned_files_dir : "./ownedFiles/"
new_files_dir : "./newFiles/"
owned_files :
        - "file6.txt"
        - "file5.txt"
        - "file7.txt"
friend_nodes :
        -
                node_name : 1
                node_port : 8081
