node_number : 2
node_port : 8082
owned_files_dir : "./ownedFiles/"
new_files_dir : "./newFiles/"
owned_files :
        - "file4.txt"
friend_nodes :
        -
                node_name : 4
                node_port : 8084
        -
                node_name : 5
                node_port : 8085
        -
                node_name : 1
                node_port : 8081

